/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 Cactus.gltf
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useEffect } from 'react'

export function Cactus(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('Model//Cactus.gltf')
  const { actions } = useAnimations(animations, group)
  console.log(actions)
  useEffect(()=>{
    actions["Bite_Front"].reset().play()
    return () => actions["Bite_Front"].stop()
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="MonsterArmature">
          <primitive object={nodes.Body} />
          <primitive object={nodes.Head} />
          <skinnedMesh name="Cactus001" geometry={nodes.Cactus001.geometry} material={materials.Texture} skeleton={nodes.Cactus001.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Model/Cactus.gltf')
