/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 Deer.gltf
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Deer(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Model/Deer.gltf')
  const { actions } = useAnimations(animations, group)
  console.log(actions)
  useEffect(()=>{
    actions["Bite_Front"].reset().play()
    return () => actions["Bite_Front"].stop()
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="MonsterArmature">
          <primitive object={nodes.Body} />
          <primitive object={nodes.Head} />
          <skinnedMesh name="Deer" geometry={nodes.Deer.geometry} material={materials.Texture} skeleton={nodes.Deer.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Model/Deer.gltf')
