/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 diamond3.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/diamond3.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.DIAMOND172.geometry} material={materials.DIAMANT} rotation={[0, -0.39, 0]} scale={[0.06, 0.04, 0.04]} />
    </group>
  )
}

useGLTF.preload('/diamond3.glb')
