/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 diamond12.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/diamond12.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Diamond_Emerald_cut.geometry} material={materials.DIAMANT} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
    </group>
  )
}

useGLTF.preload('/diamond12.glb')
