/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 glass.glb --transform --simplify
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Glass(props) {
  const { nodes, materials } = useGLTF('/Model/glass-transformed.glb')
  return (
    <group {...props} dispose={null} >
      <mesh geometry={nodes.Object004.geometry} material={materials['03 - Default']} position={[0, 1.01, 0]} rotation={[Math.PI, 0, 0]} scale={-0.01} >
        <meshBasicMaterial color={"red"}/>
      </mesh>
    </group>
  )
}

useGLTF.preload('/Model/glass-transformed.glb')
