/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 gloves.glb --transform --simplify
*/

import React, { useRef } from 'react'
import { MeshRefractionMaterial, useGLTF } from '@react-three/drei'
import { RGBELoader } from 'three-stdlib'
import { Canvas, useFrame, useLoader } from '@react-three/fiber'
export function Gloves(props) {
  const { nodes, materials } = useGLTF('/Model/gloves-transformed.glb')
  const config = {
    bounces: 3,
    aberrationStrength: 0.1,
    ior: 2.75,
    // fresnel: 1/10e98,
    color: 'red',
    fastChroma: true
    }
  const texture = useLoader(RGBELoader, 'https://dl.polyhaven.org/file/ph-assets/HDRIs/hdr/1k/aerodynamics_workshop_1k.hdr')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['default'].geometry} material={materials.Leather_Lambskin_FRONT_4529} position={[0, -4.94, 0]} scale={0.03} >
        {/* <meshStandardMaterial color={"red"}/> */}
        <MeshRefractionMaterial envMap={texture} toneMapped={false} {...config}/>
      </mesh>
    </group>
  )
}

useGLTF.preload('/Model/gloves-transformed.glb')
