/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 men.glb --transform --simplify
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Men(props) {
  const { nodes, materials } = useGLTF('/Model/men-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pattern2D_1597631.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Shape2D_1459379.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_1597630.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_1318943.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_1318942.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_2985354.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.ButtonHead_2983321.geometry} material={materials.BTN_FABRIC_FRONT_2583} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.ButtonHead_30274.geometry} material={materials.BTN_FABRIC_FRONT_2583} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.ButtonHead_34125.geometry} material={materials.BTN_FABRIC_FRONT_2583} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.ButtonHead_34218.geometry} material={materials.BTN_FABRIC_FRONT_2583} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <group rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08}>
        <mesh geometry={nodes.Pattern2D_120406_1.geometry} material={materials.hat_middle_FRONT_2555} />
        <mesh geometry={nodes.Pattern2D_120406_2.geometry} material={materials.Material3077824} />
      </group>
      <mesh geometry={nodes._1.geometry} material={materials.Material3077824} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes._2.geometry} material={materials.Material3077824} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes._3.geometry} material={materials.Material3077824} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.ButtonHead_2973964.geometry} material={materials.BTN_FABRIC_FRONT_2583} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.ButtonHead_2974166.geometry} material={materials.BTN_FABRIC_FRONT_2583} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.ButtonHead_2974234.geometry} material={materials.BTN_FABRIC_FRONT_2583} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.ButtonHead_2974301.geometry} material={materials.BTN_FABRIC_FRONT_2583} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.ButtonHead_2974395.geometry} material={materials.BTN_FABRIC_FRONT_2583} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.ButtonHead_2974514.geometry} material={materials.BTN_FABRIC_FRONT_2583} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.ButtonHead_2974632.geometry} material={materials.BTN_FABRIC_FRONT_2583} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.ButtonHead_2974739.geometry} material={materials.BTN_FABRIC_FRONT_2583} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_2985347.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_2985348.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_2985349.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_2985350.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_2985351.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_2985352.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_2985353.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_2962532.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_2962533.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_2962531.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_2962531_1.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_40457.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_40458.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_120405.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_120404_1.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_29062.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_29064.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_29044.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_29061.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_35919.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_35920.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_35921.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Shape2D_3093053.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_3114400.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Shape2D_3093052.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_3114399.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Shape2D_3120909.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_120404.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_29045.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_29040.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_29041.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_29046.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4652499.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4652500.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4652501.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4652502.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4316988.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4316987.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4323934.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4323931.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4316990.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4316987_1.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4316992.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4316989.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4323935.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4323932.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4323937.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4323931_1.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4323938.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4323933.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4323939.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4323936.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4323941.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4323942.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4323936_1.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4323936_2.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4316994.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4316991.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4316995.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4316996.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4316997.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4316998.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4779425.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4779421.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4779426.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4779427.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4779421_1.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4779421_2.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4779429.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4779430.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4779423.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4779424.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4779428.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
      <mesh geometry={nodes.Pattern2D_4779422.geometry} material={materials.hat_middle_FRONT_2555} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5.08} />
    </group>
  )
}

useGLTF.preload('/Model/men-transformed.glb')
