/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 menmodel.glb --transform --simplify
*/

import React, { useRef } from 'react'
import { MeshRefractionMaterial, useGLTF } from '@react-three/drei'
import { RGBELoader } from 'three-stdlib'
import { Canvas, useFrame, useLoader } from '@react-three/fiber'

export function MenModel(props) {
  const { nodes, materials } = useGLTF('/Model/menmodel-transformed.glb')
  const config = {
    bounces: 3,
    aberrationStrength: 0.1,
    ior: 2.75,
    // fresnel: 1/10e98,
    color: '#ffcccb',
    fastChroma: true
    }
  const texture = useLoader(RGBELoader, 'https://dl.polyhaven.org/file/ph-assets/HDRIs/hdr/1k/aerodynamics_workshop_1k.hdr')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.thick.geometry} material={materials.Leather_Lambskin_FRONT_4529} rotation={[Math.PI / 2, 0, 0]} scale={0.01} >
        <MeshRefractionMaterial envMap={texture} toneMapped={false} {...config}/>
      </mesh>
    </group>
  )
}

useGLTF.preload('/Model/menmodel-transformed.glb')
