/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 Glass08.glb --transfrom --simplify
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Glass08(props) {
  const { nodes, materials } = useGLTF('/Model/Floating/Glass08.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Glass08.geometry} material={materials.Mask_Mat} position={[-0.04, 2.51, 0.1]} scale={[0.02, 0.01, 0.01]} material-color={"green"} />
    </group>
  )
}

useGLTF.preload('/Model/Floating/Glass08.glb')
