/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 GlovesRight.glb --transfrom --simplify
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function GlovesRight(props) {
  const { nodes, materials } = useGLTF('/Model/Floating/GlovesRight.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.GlovesRight.geometry} material={materials['Gloves_Mat.002']} position={[0.8, 1.35, 0.15]} rotation={[0, 0, -1.65]} scale={0.03} />
    </group>
  )
}

useGLTF.preload('/Model/Floating/GlovesRight.glb')
