/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 GlovesLeft.glb --transfrom --simplify
*/

import React, { useRef } from 'react'
import { useGLTF,useTexture } from '@react-three/drei'
import { RGBELoader } from 'three-stdlib'
import { useLoader } from '@react-three/fiber'

export function GlovesLeft(props) {
  const { nodes, materials } = useGLTF('/Model/Floating/GlovesLeft.glb')
  const texture = useLoader(RGBELoader, 'https://dl.polyhaven.org/file/ph-assets/HDRIs/hdr/1k/aerodynamics_workshop_1k.hdr')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.GlovesLeft.geometry} material={materials.Gloves_Mat} position={[-0.8, 1.34, 0.15]} rotation={[0, 0, 2.35]} scale={0.03} material-color={"red"} >
        {/* <meshBasicMaterial color={"red"} /> */}
      </mesh>
    </group>
  )
}

useGLTF.preload('/Model/Floating/GlovesLeft.glb')
