/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 Mask21.glb --transfrom --simplify
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Mask21 (props,ref) {
  const { nodes, materials } = useGLTF('/Model/Floating/Mask21.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mask21.geometry} material={materials.Mask_Mat} position={[0.01, 2.49, 0.12]} scale={0.03} material-color={"red"} />
    </group>
  )
}

useGLTF.preload('/Model/Floating/Mask21.glb')
