/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 RightShoe.glb --transform --simplify
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function RightShoe(props) {
  const { nodes, materials } = useGLTF('/Model/Floating/RightShoe-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Diamond17.geometry} material={materials.Diamond} position={[0, 1.94, 0]} rotation={[0.04, -Math.PI / 2, 0]} scale={[1, 2, 1]} />
      <mesh geometry={nodes.Glass08.geometry} material={materials.Mask_Mat} position={[-0.04, 2.51, 0.1]} scale={[0.02, 0.01, 0.01]} />
      <mesh geometry={nodes.Mask21.geometry} material={materials.Mask_Mat} position={[0.01, 2.49, 0.12]} scale={0.03} />
      <mesh geometry={nodes.GlovesRight.geometry} material={materials.Mask_Mat} position={[0.8, 1.35, 0.15]} rotation={[0, 0, -1.65]} scale={0.03} />
      <mesh geometry={nodes.GlovesLeft.geometry} material={materials.Mask_Mat} position={[-0.8, 1.34, 0.15]} rotation={[0, 0, 2.35]} scale={0.03} />
      <mesh geometry={nodes.RightShoe.geometry} material={materials.Mask_Mat} position={[0.19, -0.06, 0.24]} scale={0.15} />
      <mesh geometry={nodes.LeftShoe.geometry} material={materials.Mask_Mat} position={[-0.31, -0.06, 0.24]} scale={0.15} />
    </group>
  )
}

useGLTF.preload('/Model/Floating/RightShoe-transformed.glb')
