/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 ShoeRight.glb --transfrom --simplify
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function RightShoe(props) {
  const { nodes, materials } = useGLTF('/Model/Floating/ShoeRight.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.RightShoe.geometry} material={materials.Shoe_Mat} position={[0.32, 0.06, -0.01]} rotation={[Math.PI / 2, 0, 0.4]} scale={0} />
    </group>
  )
}

useGLTF.preload('/Model/Floating/ShoeRight.glb')
