/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 human.glb --transform
*/

import React, { useRef,useEffect } from 'react'
import { useAnimations, useFBX, useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Human(props) {
  const modelGroup = useRef()
  const { nodes, materials } = useGLTF('/Model/human-transformed.glb')
  const {animations: walkingAnimation} = useFBX("/Model/Mutant.fbx")
  walkingAnimation[0].name = "Pradeep Selva"
  const {actions} = useAnimations(walkingAnimation, modelGroup)
  // useEffect(()=>{
  //   actions["Pradeep Selva"].reset().play()
  // },[])

  return (
    // 0.44244527793770017, 3.1014217168212497, 5.367024455738141
    // -0.17907503921057397, 0.1084975761996645, 0.019598572194239293
    <group {...props} ref={modelGroup} dispose={null} scale={0.02} >
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.human_1.geometry} material={materials.Std_Tongue} />
        <mesh geometry={nodes.human_2.geometry} material={materials.Hair} />
        <mesh geometry={nodes.human_3.geometry} material={materials.Scalp} />
        <mesh geometry={nodes.human_4.geometry} material={materials.Std_Skin_Head} />
        <mesh geometry={nodes.human_5.geometry} material={materials.Std_Skin_Body} />
        <mesh geometry={nodes.human_6.geometry} material={materials.Std_Skin_Arm} />
        <mesh geometry={nodes.human_7.geometry} material={materials.Std_Skin_Leg} />
        <mesh geometry={nodes.human_8.geometry} material={materials.Std_Nails} />
        <mesh geometry={nodes.human_9.geometry} material={materials.Std_Eyelash} />
        <mesh geometry={nodes.human_10.geometry} material={materials.Std_Tearline_R} />
        <mesh geometry={nodes.human_11.geometry} material={materials.Std_Tearline_R} />
        <mesh geometry={nodes.human_12.geometry} material={materials.Std_Eye_Occlusion_R} />
        <mesh geometry={nodes.human_13.geometry} material={materials.Std_Eye_Occlusion_R} />
        <mesh geometry={nodes.human_14.geometry} material={materials.Std_Eye_R} />
        <mesh geometry={nodes.human_15.geometry} material={materials.Std_Cornea_R} />
        <mesh geometry={nodes.human_16.geometry} material={materials.Std_Eye_R} />
        <mesh geometry={nodes.human_17.geometry} material={materials.Std_Cornea_R} />
        <mesh geometry={nodes.human_18.geometry} material={materials.Std_Upper_Teeth} />
        <mesh geometry={nodes.human_19.geometry} material={materials.Std_Lower_Teeth} />
        <mesh geometry={nodes.human_20.geometry} material={materials.Beard_01} />
        <mesh geometry={nodes.human_21.geometry} material={materials.Beard_02} />
        <mesh geometry={nodes.human_22.geometry} material={materials.Beard_02} />
        <mesh geometry={nodes.human_23.geometry} material={materials.Beard_02} />
        <mesh geometry={nodes.human_24.geometry} material={materials.Male_Bushy} />
        <mesh geometry={nodes.human_25.geometry} material={materials.Male_Bushy_Base} />
        <mesh geometry={nodes.human_26.geometry} material={materials.Boots} />
        <mesh geometry={nodes.human_27.geometry} material={materials.Jeans} />
        <mesh geometry={nodes.human_28.geometry} material={materials.Plaid_Punk_Shirt} />
      </group>
    </group>
  )
}

useGLTF.preload('/Model/human-transformed.glb')
