/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 scene.gltf
Author: Frank Rennau (https://sketchfab.com/rennau)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/diamonds-cuts-collection-2d4bc262e1c24c3097dc20d4e2b0e2c5
Title: Diamonds cuts Collection.
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[6.98, 0.29, -11.44]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={2.09}>
          <mesh geometry={nodes.Diamond_Emerald_cut_DIAMANT_0.geometry} material={materials.DIAMANT} position={[0, 0, 0.02]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.95, 0.97, 0.95]} />
        </group>
        <group position={[-3.22, 0.35, -11.49]} rotation={[-Math.PI / 2, 0, 0]} scale={[5.13, 5.13, 3.86]}>
          <mesh geometry={nodes.DIAMOND170_DIAMANT_0.geometry} material={materials.DIAMANT} position={[0, 0, -0.07]} />
        </group>
        <group position={[-3.11, 0.33, -7.02]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.DIAMOND171_DIAMANT_0.geometry} material={materials.DIAMANT} position={[0.09, -0.04, -0.27]} rotation={[0, 0, -0.38]} scale={[5.13, 4.26, 3.86]} />
        </group>
        <group position={[1.02, 0.35, -11.37]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.DIAMOND172_DIAMANT_0.geometry} material={materials.DIAMANT} position={[0, 0, -0.29]} rotation={[0, 0, -0.39]} scale={[6.37, 4.17, 3.86]} />
        </group>
        <group position={[-1.1, 0.29, -7.08]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={2.09}>
          <mesh geometry={nodes.Diamond_Emerald_cut001_DIAMANT_0.geometry} material={materials.DIAMANT} position={[0, 0, 0.02]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.95, 0.97, 0.95]} />
        </group>
        <group position={[-3.22, 0.6, -10.4]} rotation={[Math.PI, 0, 0]} scale={[5.13, 5.13, 3.86]}>
          <mesh geometry={nodes.DIAMOND173_DIAMANT_0.geometry} material={materials.DIAMANT} position={[0, 0, -0.07]} />
        </group>
        <group position={[-3.02, 0.6, -6.02]} rotation={[-Math.PI, 0, 0]} scale={[1, 0.83, 1]}>
          <mesh geometry={nodes.DIAMOND174_DIAMANT_0.geometry} material={materials.DIAMANT} position={[0, 0, -0.29]} rotation={[0, 0, -0.38]} scale={[5.13, 5.13, 3.86]} />
        </group>
        <group position={[1.02, 0.6, -10.41]} rotation={[-Math.PI, 0, 0]} scale={[1.24, 0.81, 1]}>
          <mesh geometry={nodes.DIAMOND175_DIAMANT_0.geometry} material={materials.DIAMANT} position={[0, 0, -0.29]} rotation={[0, 0, -0.39]} scale={[5.13, 5.13, 3.86]} />
        </group>
        <group position={[6.98, 0.53, -10.4]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={2.09}>
          <mesh geometry={nodes.Diamond_Emerald_cut003_DIAMANT_0.geometry} material={materials.DIAMANT} position={[0, 0, 0.02]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.95, 0.97, 0.95]} />
        </group>
        <group position={[3.04, 0.32, -11.36]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Plane008_DIAMANT_0.geometry} material={materials.DIAMANT} position={[0, 0, 0.31]} />
        </group>
        <group position={[-1.1, 0.29, -5.9]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={2.09}>
          <mesh geometry={nodes.Diamond_Emerald_cut004_DIAMANT_0.geometry} material={materials.DIAMANT} position={[0, 0, 0.02]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.95, 0.97, 0.95]} />
        </group>
        <group position={[-3.22, 0.36, -9.23]} rotation={[Math.PI / 2, 0, 0]} scale={[5.13, 5.13, 3.86]}>
          <mesh geometry={nodes.DIAMOND176_DIAMANT_0.geometry} material={materials.DIAMANT} position={[0, 0, -0.07]} />
        </group>
        <group position={[1.02, 0.36, -9.35]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.DIAMOND177_DIAMANT_0.geometry} material={materials.DIAMANT} position={[0, 0, -0.29]} rotation={[0, 0, -0.39]} scale={[6.37, 4.17, 3.86]} />
        </group>
        <group position={[6.98, 0.42, -9.28]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={2.09}>
          <mesh geometry={nodes.Diamond_Emerald_cut005_DIAMANT_0.geometry} material={materials.DIAMANT} position={[0, 0, 0.02]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.95, 0.97, 0.95]} />
        </group>
        <group position={[3.04, 0.4, -9.36]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Plane019_DIAMANT_0.geometry} material={materials.DIAMANT} position={[0, 0, 0.31]} />
        </group>
        <group position={[-3.11, 0.32, -4.7]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.DIAMOND178_DIAMANT_0.geometry} material={materials.DIAMANT} position={[0.09, -0.04, -0.27]} rotation={[0, 0, -0.38]} scale={[5.13, 4.26, 3.86]} />
        </group>
        <group position={[-1.1, 0.36, -4.64]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={2.09}>
          <mesh geometry={nodes.Diamond_Emerald_cut006_DIAMANT_0.geometry} material={materials.DIAMANT} position={[0, 0, 0.02]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.95, 0.97, 0.95]} />
        </group>
        <mesh geometry={nodes.Plane004_DIAMANT_0.geometry} material={materials.DIAMANT} position={[-1.1, 0.31, -10.6]} rotation={[Math.PI, 0, 0]} />
        <mesh geometry={nodes.Plane005_DIAMANT_0.geometry} material={materials.DIAMANT} position={[-1.1, 0.5, -11.48]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Plane006_DIAMANT_0.geometry} material={materials.DIAMANT} position={[5.11, 0.55, -6.88]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Plane007_DIAMANT_0.geometry} material={materials.DIAMANT} position={[7, 0.51, -7.05]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Plane009_DIAMANT_0.geometry} material={materials.DIAMANT} position={[3.04, 0.46, -10.68]} rotation={[Math.PI, 0, 0]} />
        <mesh geometry={nodes.Plane010_DIAMANT_0.geometry} material={materials.DIAMANT} position={[7, 0.51, -6]} rotation={[Math.PI, 0, 0]} />
        <mesh geometry={nodes.Plane011_DIAMANT_0.geometry} material={materials.DIAMANT} position={[5.09, 0.55, -6.01]} rotation={[Math.PI, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Plane012_DIAMANT_0.geometry} material={materials.DIAMANT} position={[1.02, 0.64, -7.08]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Plane013_DIAMANT_0.geometry} material={materials.DIAMANT} position={[1.02, 0.64, -6.19]} rotation={[Math.PI, 0, 0]} />
        <mesh geometry={nodes.Plane014_DIAMANT_0.geometry} material={materials.DIAMANT} position={[5.2, 0.84, -10.65]} rotation={[Math.PI, 0, 0]} />
        <mesh geometry={nodes.Plane015_DIAMANT_0.geometry} material={materials.DIAMANT} position={[5.2, 0.84, -11.48]} rotation={[-1.51, 0, 0]} />
        <mesh geometry={nodes.Plane016_DIAMANT_0.geometry} material={materials.DIAMANT} position={[3.08, 0.62, -7.12]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Plane017_DIAMANT_0.geometry} material={materials.DIAMANT} position={[3.08, 0.62, -6.15]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes.Plane018_DIAMANT_0.geometry} material={materials.DIAMANT} position={[-1.1, 0.21, -9.24]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Plane020_DIAMANT_0.geometry} material={materials.DIAMANT} position={[5.2, -0.13, -9.24]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Plane021_DIAMANT_0.geometry} material={materials.DIAMANT} position={[5.11, 0.1, -4.83]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Plane022_DIAMANT_0.geometry} material={materials.DIAMANT} position={[7, 0.14, -4.67]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Plane023_DIAMANT_0.geometry} material={materials.DIAMANT} position={[1.02, 0.01, -4.64]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Plane024_DIAMANT_0.geometry} material={materials.DIAMANT} position={[3.08, 0.03, -4.6]} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
